## Data Collection and Feature Engineering steps

In [5]:
import pandas as pd

# Download and load the train data:
train_data_url = 'https://raw.githubusercontent.com/google-research/google-research/2adf640a14f11025ae5a9d0ec493b78530d276d3/goemotions/data/train.tsv'

# Load the files into dataframes
train_data = pd.read_csv(train_data_url, sep='\t')

# comment will be the only feature
# emotion will be the target (multiple labels)
header = ["comment", "emotion", "id"]
train_data.columns = header

# Tokenize the comments using the BERT tokenizer (Convert comments into Tokens)
from transformers import BertTokenizerFast
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')
tokenized_comments = tokenizer(train_data['comment'].to_list(), padding=True, truncation=True, return_tensors='pt')

# Convert tokenized data to numpy arrays
X = tokenized_comments['input_ids'].numpy()
y = train_data['emotion'].values

In [13]:
from sklearn.model_selection import train_test_split

# Convert tokenized data to numpy arrays
X = tokenized_comments['input_ids'].numpy()
y = train_data['emotion'].values

print("X = ", X)
print("y = ", y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X =  [[ 101 2085 2065 ...    0    0    0]
 [ 101 2339 1996 ...    0    0    0]
 [ 101 2000 2191 ...    0    0    0]
 ...
 [ 101 2054 2024 ...    0    0    0]
 [ 101 2062 2066 ...    0    0    0]
 [ 101 5959 1996 ...    0    0    0]]
y =  ['27' '2' '14' ... '3' '13' '17']


In [6]:
from transformers import BertForSequenceClassification
# Load the BERT model
# we will use the bert-base-uncased model
# this model will classify the comments into 28 emotions

model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=28)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Going back to the research question, the research question could be "Can we predict the sentiment of a text?"

Our first research question is now:

**How can different transformer-based models classify textual emotions effectively?**

We start with the BERT Classifier.